refactor(embed): 임베드 생성 방식 리팩토링
team-crescendo/Crenata pull request #23
Opened 2023-05-10 13:31 UTC by SaidBySolo

이러한 리팩토링으로 우리는 더 나은 유지보수와 용이한 개발을 가능하게 합니다.

2023-05-11 14:36 UTC, star0202 requested changes

2023-05-11 14:36 UTC, star0202 commented on crenata/abc/builder.py
> +    def _build(self, data: Any):
```suggestion
    def _build(self, data: Any) -> None:
```
타입 어노테이션 추가

2023-05-11 14:36 UTC, star0202 commented on crenata/abc/builder.py
> +    def build(cls, data: Any):
```suggestion
    def build(cls, data: Any) -> Embed:
```
타입 어노테이션 추가

2023-05-11 14:36 UTC, star0202 commented on crenata/abc/builder.py
> +    def build_with_apply_private_preference(cls, data: Any, private: bool):
```suggestion
    def build_with_apply_private_preference(cls, data: Any, private: bool) -> Embed:
```
타입 어노테이션 추가

2023-05-11 14:36 UTC, star0202 commented on crenata/discord/embed/meal.py
> +        return f"{emoji.get(string, None)} {string}"
```suggestion
        return f"{emoji.get(string, '❓')} {string}"
```
기본값을 '❓'로 설정

2023-05-11 14:36 UTC, star0202 commented on crenata/discord/embed/meal.py
> +    def _build(self, data: Any):
```suggestion
    def _build(self, data: Any) -> None:
```
타입 어노테이션 추가

2023-05-11 14:36 UTC, star0202 commented on crenata/discord/embed/meal.py
> +    def _build(self, data: Any):
```suggestion
    def _build(self, data: Any) -> None:
```
타입 어노테이션 추가

2023-05-11 14:36 UTC, star0202 commented on crenata/discord/embed/meal.py
> +class MealEmbedBuilder(AbstractEmbedBuilder):
```suggestion
class MealEmbedBuilder(AbstractEmbedBuilder):
    def __init__(self) -> None:
        super().__init__()

```
`AbstractEmbedBuilder`의 `__init__` 호출

2023-05-11 16:33 UTC, bluefcat commented on crenata/discord/embed/meal.py
> +    def if_applied_private_preference_is_true_hide_school_name(
이거 함수명 너무 긴 것 같은데 ``follow_private_preference`` 정도로 바꾸는 건 어떻게 생각하시나요

2023-05-24 01:16 UTC, star0202 submitted a review, later dismissed

2023-05-24 11:44 UTC, bluefcat reviewed
읽어보고 의견 몇개 더 냈습니다

2023-05-24 11:44 UTC, bluefcat commented on crenata/discord/embed/meal.py
> +    def add_emoji(self, string: Literal["조식", "중식", "석식"]) -> str:
이것말고 몇개 더 있을 것 같긴한데 이런 얘들은 class 내부에서만 접근하는 그림 밖에 안보이니까 그냥 ``__add_emoji`` 해서 private로 달아놔도 괜찮을 것 같다고 생각해요

2023-05-24 11:44 UTC, bluefcat commented on crenata/abc/builder.py
> +        return school_name
```suggestion
    def follow_private_preference(self, **kwargs: str) -> Dict[str]:
        if self.private:
            return {key: "비공개" for key, _ in kwargs.items()}
        return kwargs
```

이거 클래스가 AbstractEmbedBuilder니까 아예 일반화 해보는건 어떤가요?

2023-05-24 11:50 UTC, bluefcat commented on crenata/abc/builder.py
> +        return school_name
되면 Namespace로 반환받아도 괜찮을 것 같아요

2023-05-27 02:05 UTC, star0202 requested changes
method가 아니기 떄문에 private method를 의미하는 __를 제거했습니다

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/meal.py
> +def __add_emoji(string: Literal["조식", "중식", "석식"]) -> str:
```suggestion
def add_emoji(string: Literal["조식", "중식", "석식"]) -> str:
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/meal.py
> +def __parse_br_tag(string: str) -> str:
```suggestion
def parse_br_tag(string: str) -> str:
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +def __add_paragraph(string: str) -> str:
```suggestion
def add_paragraph(string: str) -> str:
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +def __parse_homepage_url(url: str) -> Optional[str]:
```suggestion
def parse_homepage_url(url: str) -> Optional[str]:
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +def __handle_english_school_name(school_name: Optional[str]) -> str:
```suggestion
def handle_english_school_name(school_name: Optional[str]) -> str:
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +def __handle_coeducation(result: Any) -> str:
```suggestion
def handle_coeducation(result: Any) -> str:
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +def __handle_school_type(result: Any) -> str:
```suggestion
def handle_school_type(result: Any) -> str:
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/meal.py
> +            name=f"{__add_emoji(result.MMEAL_SC_NM)} ({result.CAL_INFO})",
```suggestion
            name=f"{add_emoji(result.MMEAL_SC_NM)} ({result.CAL_INFO})",
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/meal.py
> +            value=f"{__parse_br_tag(result.DDISH_NM)}",
```suggestion
            value=f"{parse_br_tag(result.DDISH_NM)}",
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +        return __add_paragraph(school_name)
```suggestion
        return add_paragraph(school_name)
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +    kind += f"\n> { __handle_coeducation(result)}"
```suggestion
    kind += f"\n> {handle_coeducation(result)}"
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +    kind = __handle_school_type(result)
```suggestion
    kind = handle_school_type(result)
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +    embed.description = __handle_english_school_name(result.ENG_SCHUL_NM)
```suggestion
    embed.description = handle_english_school_name(result.ENG_SCHUL_NM)
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +    embed.add_field(name="❓ 학교 분류", value=__add_paragraph(kind))
```suggestion
    embed.add_field(name="❓ 학교 분류", value=add_paragraph(kind))
```

2023-05-27 02:05 UTC, star0202 commented on crenata/discord/embed/school.py
> +    if url := __parse_homepage_url(result.HMPG_ADRES):
```suggestion
    if url := parse_homepage_url(result.HMPG_ADRES):
```

2023-05-27 02:22 UTC, SaidBySolo commented
해당 모듈내에서만 사용됩니다.

이러한 api를 노출시키고 싶지않습니다.

2023-05-27 02:44 UTC, bluefcat commented on crenata/discord/commands/school/meal.py
> +    select_allergy_ui.add_option(label="16.쇠고기, 17.오징어, 18.조개류")
select_allergy_ui의 add_option의 내용은 고정값이니까 AllergyUI를 선언해준 함수 내부에서 추가하는 것 보다
그냥 AllergyUI 자체에서 만들어서 던져줘도 될 것 같다는 생각을 하는데 어떻게 생각하시나요?

2023-05-27 03:47 UTC, SaidBySolo commented on crenata/discord/commands/school/meal.py
> +    select_allergy_ui.add_option(label="16.쇠고기, 17.오징어, 18.조개류")
좋은 의견입니다

2023-05-28 13:35 UTC, star0202 approved these changes

2023-05-29 02:08 UTC, bluefcat approved these changes
괜찮은것 같습니다. 
사소한 의문 하나 남겼는데 시간되시면 답변해주세요

2023-05-29 02:08 UTC, bluefcat commented on crenata/discord/embed/meal.py
> +def _add_emoji(string: Literal["조식", "중식", "석식"]) -> str:
사소한 의문인데 ``__add_emoji`` 에서 ``_add_emoji``로 바뀐 이유가 있나요?

2023-05-29 02:10 UTC, SaidBySolo commented on crenata/discord/embed/meal.py
> +def _add_emoji(string: Literal["조식", "중식", "석식"]) -> str:
보통 더블 언더바가 아니라 싱글언더바로 표현합니다.

https://peps.python.org/pep-0008/#naming-conventions

> _single_leading_underscore: weak “internal use” indicator. E.g. from M import * does not import objects whose names start with an underscore.

2023-05-29 02:16 UTC, bluefcat commented on crenata/discord/embed/meal.py
> +def _add_emoji(string: Literal["조식", "중식", "석식"]) -> str:
오... 확인했습니다

2023-05-29 02:17 UTC, merged