chore: deploy with docker
team-crescendo/Crenata pull request #38
Opened 2023-07-02 11:52 UTC by star0202

closes #37

2023-07-04 13:07 UTC, SaidBySolo requested changes
docker-compose에 postgres 구성도 추가되어야 할것 같아요.

* 굳이 .ENV 안불러오고 그냥 environment 필드 사용해도 될 것 같아요
* 도커 용량을 더 줄이고싶어요. 
  * 스테이지 나눠서 종속성만 가질수있게 하면 좋을 것 같아요
* 즉시 배포가능하도록 하고싶어요
* 도커 빌드가 정상적으로 되는지에 대한 플로우도 필요할 것 같아요

2023-07-05 11:35 UTC, SaidBySolo commented on Dockerfile
> +    poetry install --no-interaction
스타일 및 테스트 종속성은 실행시에 필요없어요

2023-08-23 13:10 UTC, SaidBySolo approved these changes

2023-08-23 13:20 UTC, bluefcat approved these changes

2023-08-23 13:57 UTC, merged