BREAKING CHANGE: refactoring structure
team-crescendo/Crenata pull request #47
Opened 2023-11-01 00:56 UTC by SaidBySolo

2023-11-07 11:11 UTC, SaidBySolo reviewed
셀프 리뷰

2023-11-12 02:11 UTC, SaidBySolo commented on crenata/application/commands/school/setup.py
> +                content="성공적으로 수정되었습니다.",
이곳 또한 마찬가지로 Strings 에 통합적으로 들어가야함

2023-11-12 02:11 UTC, SaidBySolo commented on crenata/application/commands/school/timetable.py
> +    await interaction.edit_original_response(content="시간표를 가져왔습니다.")
위와 동일

2023-11-12 02:11 UTC, SaidBySolo commented on crenata/application/commands/school/timetable.py
> +        content="시간표를 가져오는 중 입니다.", embed=None, view=None
위와 동일

2023-11-12 02:11 UTC, SaidBySolo commented on crenata/application/commands/school/timetable.py
> +            content="시간표가 없습니다.", embed=None, view=None
Strings에 들어가야함

2023-11-12 02:11 UTC, SaidBySolo commented on crenata/application/error/callback.py
> +@error_handler.handle_this_exception(DuplicateUser, SchoolInfoNotFound)
핸들이 안된 에러들이 많음

2023-11-12 02:11 UTC, SaidBySolo commented on crenata/application/error/callback.py
> +@error_handler.handle_this_exception(MealNameNotFound)
여기도 마찬가지로 핸들이 안된 에러들이 많음

2023-11-12 08:45 UTC, SaidBySolo reviewed
셀프 리뷰

2023-11-12 08:45 UTC, SaidBySolo commented on crenata/application/interaction.py
> +    )
embed 따로 빼놔야함

2023-11-12 08:45 UTC, SaidBySolo commented on crenata/application/interaction.py
> +                "명령어 실행자만 상호작용이 가능합니다.", ephemeral=True
이것도 대사 따로 빼놔야함

2023-11-12 08:45 UTC, SaidBySolo commented on crenata/application/commands/exit.py
> +                    content="탈퇴 되었습니다.", embed=None, view=None
대사 따로 빼두어야함

2023-11-12 08:45 UTC, SaidBySolo commented on crenata/application/commands/exit.py
> +        )
임베드 따로 빼두어야고 CrenataEmbed로 사용해야함

2023-11-12 11:46 UTC, SaidBySolo commented
preferences쪽 커맨드 작업해야함.

2023-11-12 13:10 UTC, star0202 requested changes
Strings를 용도별로 분리하는 편이 좋아 보임

2023-11-13 11:32 UTC, star0202 requested changes

2023-11-13 11:32 UTC, star0202 commented on crenata/application/commands/school/setup.py
> +            await update_school_info_usecase.execute(interaction.user.id, school_info)
가입했는지 체크하는 과정이 없음

2023-11-13 11:32 UTC, star0202 commented on crenata/core/user/usecases/get.py
> +            raise SchoolInfoNotFound
유저가 가입했는지 확인해야 하는 용도로 이 UseCase를 사용할 계획이라면 school_info의 존재 여부는 다른 방식으로 확인하는 게 좋아 보임

2023-11-13 11:32 UTC, star0202 commented on crenata/application/view/paginator.py
> +        self.embeds = embeds
1/n같은 인덱스를 모든 embed에 footer로 넣으면 좋을 것 같음

2023-11-13 11:32 UTC, star0202 commented on crenata/infrastructure/neispy/meal/domain/repository.py
> +        r = await self.neispy.mealServiceDietInfo(
DataNotFound 에러를 핸들하지 않음

2023-11-13 11:32 UTC, star0202 commented on crenata/infrastructure/neispy/timetable/domain/repository.py
> +        r = await func(
DataNotFound 에러를 핸들하지 않음

2023-11-13 11:32 UTC, star0202 commented on crenata/application/commands/school/timetable.py
> +        await interaction.edit_original_response(
original response가 없어 NotFound 에러 발생

2023-11-13 11:32 UTC, star0202 commented on crenata/application/commands/school/timetable.py
> +    await interaction.edit_original_response(
original response가 없어 NotFound 에러 발생

2023-11-13 11:32 UTC, star0202 commented on crenata/infrastructure/sqlalchemy/user/domain/repository.py
> +                    user_schema.to_entity()
```py
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
```

2023-11-13 11:33 UTC, star0202 commented
프로필 명령어 개발 필요

2023-11-17 11:02 UTC, star0202 commented on crenata/application/commands/school/setup.py
> +            await update_school_info_usecase.execute(interaction.user.id, school_info)
@SaidBySolo

2023-11-17 11:02 UTC, star0202 commented on crenata/core/user/usecases/get.py
> +            raise SchoolInfoNotFound
@SaidBySolo

2023-11-17 11:02 UTC, star0202 commented on crenata/application/view/paginator.py
> +        self.embeds = embeds
@SaidBySolo

2023-11-17 11:02 UTC, star0202 commented on crenata/infrastructure/neispy/meal/domain/repository.py
> +        r = await self.neispy.mealServiceDietInfo(
@SaidBySolo

2023-11-17 11:02 UTC, star0202 commented on crenata/infrastructure/neispy/timetable/domain/repository.py
> +        r = await func(
@SaidBySolo

2023-11-17 11:02 UTC, star0202 commented on crenata/application/commands/school/timetable.py
> +        await interaction.edit_original_response(
@SaidBySolo

2023-11-17 11:02 UTC, star0202 commented on crenata/application/commands/school/timetable.py
> +    await interaction.edit_original_response(
@SaidBySolo

2023-11-17 11:02 UTC, star0202 commented on crenata/infrastructure/sqlalchemy/user/domain/repository.py
> +                    user_schema.to_entity()
@SaidBySolo

2023-11-17 11:03 UTC, star0202 commented
> 프로필 명령어 개발 필요

@cuizzang

2023-11-17 11:03 UTC, star0202 commented
core/strings.py 대사 나누기 @star0202

2023-11-19 07:42 UTC, closed without merging