명령어의 date 인자에 “내일” 키워드 인식
team-crescendo/Crenata pull request #9
Opened 2023-02-18 07:17 UTC by star0202

## 추가된 기능
- `/학교 급식`과 `/학교 시간표` 명령어의 `date` 인자에서 "내일" 키워드를 인식해 내일 날짜를 사용 - #3

2023-02-18 07:19 UTC, star0202 commented
음 커밋 메세지에서 뭐가 문제인지 모르겠네요..

2023-02-19 06:34 UTC, SaidBySolo commented
close #9

2023-02-19 06:44 UTC, SaidBySolo requested changes
이외에는 전부 좋아보여요 :D

2023-02-19 06:44 UTC, SaidBySolo commented on crenata/utils/datetime.py
> +        return None
```suggestion
    return None
```

다음과 같은 경우에는 else 표현식이 필요없을것 같습니다.

2023-02-19 12:43 UTC, star0202 commented on crenata/utils/datetime.py
> +        return None
4c1b5c65b03ee817cc9b771ef9242c84a0d69b71

2023-02-19 13:15 UTC, SaidBySolo approved these changes
수고하셨습니다 👏 

기여 감사합니다!

2023-02-19 13:15 UTC, merged